# Generated by Django 3.1 on 2020-09-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=70)),
                ('zip_code', models.CharField(max_length=70)),
            ],
        ),
    ]
