# Generated by Django 3.1 on 2020-09-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderupdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
