# Generated by Django 3.1 on 2020-09-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('heading_one', models.CharField(default='', max_length=500)),
                ('heading_two', models.CharField(default='', max_length=500)),
                ('heading_three', models.CharField(default='', max_length=500)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='store/images')),
            ],
        ),
    ]
